CREATE OR REPLACE PROCEDURE SP_POPULATE_ADDRESS(P_USER_ID IN VARCHAR2)
IS
  V_ID       VARCHAR2(36);
  CURSOR ADDRESS_CURSOR
  IS
    SELECT ADDRESS FROM SRC_USER
  UNION
  SELECT ADDRESS FROM SRC_CENTERS
  UNION
  SELECT ACADEMIC_SCHOOL FROM SRC_COURSE;
  ADDRESS_REC VARCHAR2(200);
BEGIN
  OPEN ADDRESS_CURSOR;
  LOOP
    FETCH ADDRESS_CURSOR INTO ADDRESS_REC;
    EXIT
  WHEN ADDRESS_CURSOR%NOTFOUND;
    V_ID := SYS_GUID();
    INSERT
    INTO TAR_ADDRESS
      (
        ID,
        ADDRESS,
        CREATED_BY,
        UPDATED_BY
      )
      VALUES
      (
        V_ID,
        ADDRESS_REC,
        P_USER_ID,
        P_USER_ID
      );
  END LOOP;
  CLOSE ADDRESS_CURSOR;
  COMMIT;
EXCEPTION
WHEN OTHERS THEN
  CLOSE ADDRESS_CURSOR;
  RAISE;
END SP_POPULATE_ADDRESS;
/
DECLARE
BEGIN
  SP_POPULATE_ADDRESS('NIMISH');
END;
/