CREATE OR REPLACE PROCEDURE SP_POPULATE_COURSE(P_USER_ID IN VARCHAR2)
IS
  V_ID       VARCHAR2(36);
  V_IS_ACTIVE VARCHAR2(10) := 'TRUE';
  V_BASE_COURSE VARCHAR2(10) := 'TRUE';
  CURSOR COURSE_CURSOR
  IS
    SELECT DISTINCT COURSE_NAME FROM SRC_COURSE_ENROLLMENT;
  COURSE_REC VARCHAR2(200);
BEGIN
  OPEN COURSE_CURSOR;
  LOOP
    FETCH COURSE_CURSOR INTO COURSE_REC;
    EXIT
  WHEN COURSE_CURSOR%NOTFOUND;
    V_ID := SYS_GUID();
    INSERT
    INTO TAR_COURSE
      (
        ID,
        NAME,
        BASE_COURSE,
        IS_ACTIVE,
        CREATED_BY,
        UPDATED_BY
      )
      VALUES
      (
        V_ID,
        COURSE_REC,
        V_BASE_COURSE,
        V_IS_ACTIVE,
        P_USER_ID,
        P_USER_ID
      );
  END LOOP;
  CLOSE COURSE_CURSOR;
  COMMIT;
EXCEPTION
WHEN OTHERS THEN
  CLOSE COURSE_CURSOR;
  RAISE;
END SP_POPULATE_COURSE;
/
DECLARE
BEGIN
  SP_POPULATE_COURSE('NIMISH');
END;
/