CREATE OR REPLACE
PROCEDURE SP_POPULATE_EXAM_CENTER(
    P_USER_ID IN VARCHAR2)
IS
  V_ID VARCHAR2(36);
  V_NAME SRC_CENTERS.NAME%TYPE;
  V_IS_ACTIVE    NUMBER(1);
  V_LOCATION_ID    VARCHAR2(36);
  V_ADDRESS_ID   VARCHAR2(36);
BEGIN
  FOR REC IN
  ( SELECT NAME, ACTIVE_STATUS, REGION, ADDRESS FROM SRC_CENTERS
  )
  LOOP
    V_ID                := SYS_GUID();
    V_NAME              := REC.NAME;
    IF REC.ACTIVE_STATUS = 'TRUE' THEN
      V_IS_ACTIVE       := 1;
    ELSE
      V_IS_ACTIVE := 0;
    END IF;
    SELECT ID INTO V_LOCATION_ID FROM TAR_LOCATION WHERE NAME = REC.REGION;
    SELECT ID INTO V_ADDRESS_ID FROM TAR_ADDRESS WHERE ADDRESS = REC.ADDRESS;
    INSERT
    INTO TAR_EXAM_CENTER
      (
        ID,
        NAME,
        IS_ACTIVE,
        ADDRESS_ID,
        LOCATION_ID,
        CREATED_BY,
        UPDATED_BY,
        DELETED_BY
      )
      VALUES
      (
        V_ID,
        V_NAME,
        V_IS_ACTIVE,
        V_LOCATION_ID,
        V_ADDRESS_ID,
        P_USER_ID,
        P_USER_ID,
        NULL
      );
    COMMIT;
  END LOOP;
EXCEPTION
WHEN OTHERS THEN
  DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
  ROLLBACK;
  RAISE;
END SP_POPULATE_EXAM_CENTER;
/
DECLARE
BEGIN
  SP_POPULATE_EXAM_CENTER('NIMISH');
END;
/