CREATE OR REPLACE
PROCEDURE SP_POPULATE_LOCATION_COORDINATOR(
    P_USER_ID IN VARCHAR2)
IS
  V_ID VARCHAR2(36);
  V_IS_PRIMARY NUMBER(1) := 0;
  V_LOCATION_ID  VARCHAR2(36);
  V_USER_ID    VARCHAR2(36);
  CURSOR CENTER_CURSOR
  IS
    SELECT * FROM SRC_CENTERS;
BEGIN
  FOR CENTER_REC IN CENTER_CURSOR
  LOOP
    V_ID                := SYS_GUID();
    SELECT ID INTO V_LOCATION_ID FROM TAR_REGION WHERE CENTER_REC.REGION=NAME;
    SELECT ID
    INTO V_USER_ID
    FROM TAR_USER
    WHERE PERSONAL_EMAIL=CENTER_REC.REGIONAL_COORDINATOR;
    SELECT COUNT(*) INTO V_IS_PRIMARY FROM TAR_LOCATION_COORDINATOR;
    IF V_IS_PRIMARY=0 THEN
      V_IS_PRIMARY:=1;
    ELSE
      V_IS_PRIMARY:=0;
    END IF;
    INSERT
    INTO TAR_LOCATION_COORDINATOR
      (
        ID,
        IS_PRIMARY,
        REGION_ID,
        USER_ID,
        CREATED_BY,
        UPDATED_BY
      )
      VALUES
      (
        V_ID,
        V_IS_PRIMARY,
        V_LOCATION_ID,
        V_USER_ID,
        P_USER_ID,
        P_USER_ID
      );
  END LOOP;
END SP_POPULATE_LOCATION_COORDINATOR;
/
BEGIN
  SP_POPULATE_LOCATION_COORDINATOR('NIMISH');
END;
/