CREATE OR REPLACE
PROCEDURE SP_POPULATE_REGION_COORDINATOR(
    P_USER_ID IN VARCHAR2)
IS
  V_IS_PRIMARY NUMBER(1) := 0;
  V_REGION_ID  VARCHAR2(36);
  V_USER_ID    VARCHAR2(36);
  CURSOR REGION_CURSOR
  IS
    SELECT * FROM SRC_REGION;
BEGIN
  FOR REGION_REC IN REGION_CURSOR
  LOOP
    SELECT ID INTO V_REGION_ID FROM TAR_REGION WHERE REGION_REC.REGION_NAME=NAME;
    SELECT ID
    INTO V_USER_ID
    FROM TAR_USER
    WHERE PERSONAL_EMAIL=REGION_REC.REGIONAL_COORDINATOR;
    SELECT COUNT(*) INTO V_IS_PRIMARY FROM TAR_REGION_COORDINATOR;
    IF V_IS_PRIMARY=0 THEN
      V_IS_PRIMARY:=1;
    ELSE
      V_IS_PRIMARY:=0;
    END IF;
    INSERT
    INTO TAR_REGION_COORDINATOR
      (
        IS_PRIMARY,
        REGION_ID,
        USER_ID,
        CREATED_BY,
        UPDATED_BY
      )
      VALUES
      (
        V_IS_PRIMARY,
        V_REGION_ID,
        V_USER_ID,
        P_USER_ID,
        P_USER_ID
      );
  END LOOP;
END SP_POPULATE_REGION_COORDINATOR;
/
BEGIN
  SP_POPULATE_REGION_COORDINATOR('NIMISH');
END;
/